version: '3.3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  api:
    build:
      context: ./Backend
    image: my-api:v1
    restart: on-failure
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
      PYTHONUNBUFFERED: 1
    ports:
      - 5000:5000
    depends_on: 
      - db
    command: >
      sh -c "flask db init &&
            flask db migrate &&
            flask db upgrade &&
            flask run -h 0.0.0.0"
    volumes:
      - static:/home/app/static 

volumes:
  static:
    driver: local
